Add support for PHP 8.1
laminas/laminas-psr7bridge pull request #16
Opened 2021-10-04 15:50 UTC by arueckauer

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

PHP 8.1 support.

2021-10-21 14:31 UTC, Ocramius requested changes

2021-10-21 14:31 UTC, Ocramius commented on composer.json
> +        "phpunit/phpunit": "^9.5.10"
I think we should enable PHPUnit deprecation tracking here?

2021-10-21 16:09 UTC, arueckauer commented on composer.json
> +        "phpunit/phpunit": "^9.5.10"
Can you help me understand, how that works? Is that done in the PHPUnit configuration?

2021-10-21 16:26 UTC, Ocramius commented on composer.json
> +        "phpunit/phpunit": "^9.5.10"
Yes, see https://github.com/laminas/laminas-router/blob/44759e71620030c93d99e40b394fe9fff8f0beda/phpunit.xml.dist#L6

2021-10-21 16:53 UTC, arueckauer commented
@froschdesign Do you know what the issue with markdownlint is and how to solve it? Your expertise is greatly appreciated.

2021-10-21 17:38 UTC, froschdesign commented
@arueckauer 
For [`index.md`](https://github.com/laminas/laminas-psr7bridge/blob/1.4.x/docs/book/index.md?plain=1) use:

```markdown
<!-- markdownlint-disable -->
../../README.md
```

In the `intro.md` file add a new line at the end of the file:

```markdown
# Introduction

Code for converting [PSR-7](http://www.php-fig.org/psr/psr-7/) messages to
[laminas-http](https://docs.laminas.dev/laminas-http/) messages, and vice
versa.
<!-- new line here
```

And you can remove the unused `index.html` file.

2021-10-26 11:01 UTC, Ocramius approved these changes
LGTM :ship: 

Thanks @arueckauer!

2021-10-26 11:01 UTC, merged